innertia

medium

# It allows a call to an address that does not exist.

## Summary
In solidity, a call to a non-existent address returns `true`, causing unintended behavior in several functions present in `multicall.sol`.
## Vulnerability Detail
For example, in the `aggregate` of `multicall.sol`, there is a code `(success, returnData[i]) = call.target.call(call.callData);`.
This returns `true` even if the address does not exist, which means that the invocation was successful.
The same behavior is observed for `tryAggregate`, `tryBlockAndAggregate`, `aggregate3`, `blockAndAggregate`, and `aggregate3Value`.
## Impact
Users mistakenly believe that they have actually succeeded when in fact they have failed to execute.
## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/dev/multicall.sol#L51
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/dev/multicall.sol#L74
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/dev/multicall.sol#L121
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/dev/multicall.sol#L163
## Tool used

Manual Review

## Recommendation
Check code size before calling
